name: Deploy to Github pages

on:
  push:
    branches:
      - main
    paths:
      - "web_interface_vue/tamagometer/*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web_interface_vue/tamagometer

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: web_interface_vue/tamagometer/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
